### PR TITLE
Make errors idiomatic

### PR DESCRIPTION
**Pull request by ernestas-poskus**
@cenkalti @fatih @oguza1b 

Extracting errors to ```var``` as 'constants' to make them more usable and idiomatic

### CODE REVIEW

**Comment by ernestas-poskus** [comment]
https://github.com/koding/kite/blob/master/kontrol/postgres.go#L127 @fatih - how this should be handled ?

**Comment by fatih** [comment]
Thanks for the PR :+1: . I need to fix Travis. After that I can look at it more detailed.

**Comment by ernestas-poskus** [comment]
@fatih is my PR accepted ? should I rebase ?

**Comment by fatih** [comment]
Hi @ernestas-poskus.

Merge master again (you need to probably rebase again). Until we go the green from travis (the tests are fixed now)

**Comment by fatih** [comment]
Closing this as the code base emerged differently.

**Pull request closed without merging**
