### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by techjanitor**
Added instructions for setting up Kontrol from the repo

### CODE REVIEW

**Comment by fatih** [comment]
Can you also add a comment on how to run Kontrol after you created the initial keys? It's not urgent but would be awesome if you could :)

**Comment by tmaiaroto** [comment]
What's this about? ```multiconfig: field 'Postgres.Username' is required``` when running ```kontrol -initial```

**Comment by briantk1988** [comment]
So there's only one host that runs Kontrol, and if that host dies then that's the end? Is there a way to run Kontrol in distributed manner?

**Comment by cihangir** [comment]
@briantk1988 you can run multiple kontrols behind a load balancer, session stickiness enabled. eg: http://nginx.org/en/docs/http/load_balancing.html#nginx_load_balancing_with_ip_hash http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/US_StickySessions.html

**Comment by briantk1988** [comment]
@cihangir Thanks!

**Comment by briantk1988** [comment]
@cihangir How do I set it up so that different instances of Kontrol communicate with each other? This should be simple, but I cannot find any documentation on it. Thanks.

**Comment by cihangir** [comment]
Hi, all kontrols are identical, just start them with same configuration, no other syncronization is needed.




—
C.


On Saturday 14 Mar 2015 at 06:15, briantk1988 <notifications@github.com>, wrote:

@cihangir How do I set it up so that different instances of Kontrol communicate with each other? This should be simple, but I cannot find any documentation on it. Thanks.

**Comment by briantk1988** [comment]
@cihangir So when I register a Kite with one Kontrol instance, how do the others know?

**Comment by cihangir** [comment]
Kontrol is using ETCD or Postgresql as backed storage, since all the kontrols uses the same backend, they will have all the information.

-- 
Cihangir SAVAS
Software Engineer @ koding.com

**Comment by briantk1988** [comment]
@cihangir Thanks!

**Comment by briantk1988** [comment]
@cihangir Would you recommend running Kontrol on all nodes?

**Comment by cihangir** [comment]
It is fine for kloud, if you are OK with connection count to the storage backend.

**Comment by briantk1988** [comment]
@cihangir Thanks. I'm not very experienced with this. Would this be any problem if I use etcd as storage?

Another question is about kloud. Is there any documentation on this? The basic tutorial seems to only cover kontrol but nothing about kloud.

**Comment by cihangir** [comment]
Hi @briantk1988 we were using ETCD as backend storage, but just to uniform our backend we switched to PostgreSQL, so you should be able to use it without any problem.

>  Is there any documentation on this?
sorry, we dont have an extensive documentation for kites yet. 

i rebuilt travis build, it is passing now. cc/ @fatih

**Pull request merged**
