### PR TITLE
kontrol: expose handlers to let users customize methods

### PR DESCRIPTION
**Pull request by fatih**
This is needed so the certain methods can be altered/changed in a custom Kontrol implementation. Such as disabling authenticating or adding throttling.

### CODE REVIEW

**Comment by cihangir** [comment]
there was a problem with etcd (cluster was not up) on travis, i've rebuilt it

**Comment by cihangir** [comment]
there is a problem with ectd, can you please check?

**Comment by fatih** [comment]
Yeah problem is due: 

https://github.com/coreos/etcd/blob/master/build
http://stackoverflow.com/questions/2462317/bash-syntax-error-redirection-unexpected 

Ubuntu uses `dash`, a substitution for `bash` which doesn't support `<<<`.  It was introduced two days ago: https://github.com/coreos/etcd/commit/dd4317db434ba36c0b39c74fffee8cd6c9e0769f

**Comment by mischief** [comment]
@fatih please file a bug on the etcd repo. build script claims to use 'sh', but herestrings (`<<<`) are not sh.

**Comment by fatih** [comment]
@mischief thanks! I just did with: https://github.com/coreos/etcd/issues/3417

**Comment by fatih** [comment]
@cihangir this is ready now, I'm downloading the binaries directly right now instead of building from the sources.

**Comment by cihangir** [comment]
Thanks @fatih for looking for the root cause. IMO https://github.com/koding/kite/pull/126#issuecomment-136703850 is a good call

:+1:

**Pull request merged**
