### PR TITLE
Storage: added kite.key table

### PR DESCRIPTION
**Pull request by cihangir**

### CODE REVIEW

**Comment by fatih** [comment]
Do we need to change anything here: https://github.com/koding/kite/blob/master/.travis.yml  The username for example was `kontrolapplication`. Not sure just asking :)

**Comment by cihangir** [comment]
We shouldn't need to. I updated table.sql with latest structure (for new comers), also added migrations file for existing deployments ( eg: us :) )

**Comment by fatih** [comment]
We need a way to see why this fails. Travis doesn't show any error at all.

**Comment by fatih** [comment]
Ok found this now, when I start locally:

```
2015-06-10 16:47:30 [kontrol] ERROR    pq: null value in column "key_id" violates not-null constraint
```

I'm looking now if I can find something.

**Comment by fatih** [comment]
Ok I think it's because Kontrol tries to add a null value while registering itself. Because the code is not updated to make use of this new feature (`key_id` column` it's just fails. It need to add a random which doesn't point to any key inside the `kite.key` table.

**Comment by fatih** [comment]
Related PR: #114

**Comment by fatih** [comment]
LGTM. 

Let me pull it to PR #114 , cause it's needed as a dependency.

**Comment by fatih** [comment]
Closing this. It's merged into #114 so we can have successful builds on Travis.

**Pull request closed without merging**
