### PR TITLE
kontrol: Added NewWithoutHandlers func

### PR DESCRIPTION
**Pull request by leeola**
To allow a library user to provide their own handlers, the
`NewWithoutHandlers` function has been introduced. This creates a
kontrol instance with the normal config, but without any default
kontrol handlers. The user can then provide their own handlers, or
the existing kontrol handlers, as they see fit.

cc @cihangir @fatih

### CODE REVIEW

**Comment by fatih** [comment]
LGTM

**Comment by fatih** [comment]
The tests are failing due Travis (because we have tests that opens multiple concurrent connections and Travis's docker infrastructure can't scope with it).

**Comment by leeola** [comment]
@fatih Any recommendation on what to do with the tests then?

**Comment by cihangir** [comment]
i am working on failing tests here https://github.com/koding/kite/pull/137

**Comment by leeola** [comment]
Rebased for #137 changes, /fingerscrossed

**Pull request merged**
